spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: monomarket
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: ${DB_URL}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}

monomarket:
  jwt:
    secret: ${MONOMARKET_JWT_SECRET}
    access-token-expiration-minutes: ${MONOMARKET_JWT_ACCESS_TOKEN_EXPIRATION_MINUTES}
    refresh-token-expiration-days: ${MONOMARKET_JWT_REFRESH_TOKEN_EXPIRATION_DAYS}
  aws:
    region: ${AWS_REGION}
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: ${AWS_S3_BUCKET}
      cdn-base-url: ${AWS_S3_CDN_BASE_URL}
  oauth:
    google:
      client-id: ${GOOGLE_OAUTH_CLIENT_ID}
      client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET}
    kakao:
      client-id: ${KAKAO_OAUTH_CLIENT_ID}
      client-secret: ${KAKAO_OAUTH_CLIENT_SECRET}
    apple:
      client-id: ${APPLE_OAUTH_CLIENT_ID}
      team-id: ${APPLE_OAUTH_TEAM_ID}
      key-id: ${APPLE_OAUTH_KEY_ID}
      private-key: ${APPLE_OAUTH_PRIVATE_KEY}
